### ISSUE TITLE
why doesnt this repo include the golang specific colors?

### ISSUE THREAD

**Issue by pvinis** [chriskempson/vim-tomorrow-theme#24]
https://github.com/chriskempson/tomorrow-theme/tree/master/vim/colors this has them

**Comment by jsit** [comment]
@pvinis My fork has it; I've combined both [chriskempson/vim-tomrrow-theme](/chriskempson/vim-tomrrow-theme) and [chriskempson/tomorrow-theme](/chriskempson/tomorrow-theme):

https://github.com/jsit/vim-tomorrow-theme

**Comment by pvinis** [comment]
wow, 5 years later :) that's a long issue!

thank you for your answer. it will be useful for people arriving here from google.

👍

**Comment by jsit** [comment]
Although, truthfully, I think language-specific syntax highlighting should be handled by the language syntax file, not the colorscheme.

**Comment by pvinis** [comment]
I agree.
